### PR TITLE
fix `export` and `set` throwing an error on node >=14

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes https://github.com/EnotionZ/gpio/issues/62

### CODE REVIEW

**Review by rzr — COMMENTED** [review]
this look hackish to me, I would also use ("" + str) instead

**Comment by cherniavskii** [comment]
hey @rzr 
Thanks for looking at it!

Is there any difference between `"" + str` and `str + ""`?

**Comment by rzr** [comment]
because str's type is less known that "" , so we make sure the + operator is used from the string type, well maybe there is no differences in JS

**Comment by cherniavskii** [comment]
yeah, I think there's no difference in JS
let me know if there's anything missing in the PR :)

**Pull request merged**
